### ISSUE TITLE
Use RGD's `Fileset` for `DatasetRun` output instead of ManyToManyField

### ISSUE THREAD

**Issue by mvandenburgh** [girder/Danesfield#15]
Instead of having output files of a dataset run as a `ManyToManyField` between `DatasetRun` and `ChecksumFile`, we can leverage RGD's existing file grouping mechanism and simply have a `ForeignKey` on the `DatasetRun` that points to a `Fileset` which contains all relevant `ChecksumFiles`.

@AlmightyYakob does this make sense to do?

**Comment by AlmightyYakob** [comment]
I think this makes sense. While officially the semantics of that model in RGD is for grouping files which are intended to be ingested as one file, I think using it for this purpose here is fine :+1:
