### ISSUE TITLE
Client improvements

### ISSUE THREAD

**Issue by aashish24** [girder/Danesfield#2]
My wish list: 

1. SFA
2. Labels for intermediate products so that they could be filtered out or in
3. Better listing or viewing of the search results (geospatial extents, temporal, intermediate, output (e.g. 3D tiles) or input type, text [file name, file type]), text could be done later 
4. Cesium views (we don't need GeoJS or VTK.js)

**Comment by AlmightyYakob** [comment]
More improvements:

* Don't show output datasets when creating a new task
* Allow kicking off tasks from the explore view
* Might want to keep explore tab for showing where all datasets are

**Comment by mvandenburgh** [comment]
Some of the improvements here are done. I'll make new issues for the ones that aren't done and then close this one.

**Comment by mvandenburgh** [comment]
> 1. SFA

@aashish24 what does this mean? I don't recall.

> 2. Labels for intermediate products so that they could be filtered out or in

Filed #62 for this

> 3. Better listing or viewing of the search results (geospatial extents, temporal, intermediate, output (e.g. 3D tiles) or input type, text [file name, file type]), text could be done later

This is done. Input and output files are listed in a table and labelled with their file types

> 4. Cesium views (we don't need GeoJS or VTK.js)

This is done.

> Don't show output datasets when creating a new task

Filed #60 for this

> Allow kicking off tasks from the explore view

Filed #61 for this

> Might want to keep explore tab for showing where all datasets are

This is done. I believe the context of this was we were planning to remove the Explore tab and merge it with the Focus view, but we ultimately decided against it


@aashish24 @AlmightyYakob I think I accounted for everything here. Once I get clarification from @aashish24 on the first item, I think we can close this.
