### ISSUE TITLE
Refactor client

### ISSUE THREAD

**Issue by AlmightyYakob** [girder/Danesfield#21]
Tasks:
- Explore Tab: TBD
- Focus Tab: List output datasets, and have a "view" button that shows embedded RGD iframe (@mvandenburgh)
- Jobs Tab: Show current GUI (tasks view)
- Girder Tab: Open new tab to swagger page

Ideally each tab contains a separate view and changes route using vue-router.

**Comment by AlmightyYakob** [comment]
Thinking about this more now, the explore tab might be the place to list datasets, whereas the Focus tab might be better for viewing the files of a specific dataset (hence _Focus_). Lmk if you have any thoughts @mvandenburgh.

**Comment by mvandenburgh** [comment]
> Thinking about this more now, the explore tab might be the place to list datasets, whereas the Focus tab might be better for viewing the files of a specific dataset (hence _Focus_). Lmk if you have any thoughts @mvandenburgh.

Sounds good to me.

**Comment by mvandenburgh** [comment]
> Thinking about this more now, the explore tab might be the place to list datasets, whereas the Focus tab might be better for viewing the files of a specific dataset (hence _Focus_). Lmk if you have any thoughts @mvandenburgh.

I thought about this a bit more - should we just eliminate the "Focus tab" all together? Presumably you would click on a dataset from the Explore tab to view its files, so there's no use case for clicking the Focus tab.

**Comment by AlmightyYakob** [comment]
> I thought about this a bit more - should we just eliminate the "Focus tab" all together? Presumably you would click on a dataset from the Explore tab to view its files, so there's no use case for clicking the Focus tab.

I suppose you make a good point. I guess the main benefit in keeping it otherwise is that it would make things less cluttered, as in, explore is just for selecting datasets, and focus tab is just for viewing/visualizing the files of the currently selected dataset. I'd say for now, it's probably easier to just give ourselves more room to work, and if we think some things are redundant, we can remove them as we see fit. Is that alright with you?
