### ISSUE TITLE
Investigate integrating RGD full motion video module into GUI

### ISSUE THREAD

**Issue by AlmightyYakob** [girder/Danesfield#38]
This is an investigative task to see how much effort it would be to use the FMV module in Danesfield to display video files to be run with [TeleSculptor](https://github.com/Kitware/TeleSculptor). This would be need to be used in a similar manner to how we currently use Cesium directly in our Vue app, possibly within the same viewer.

 We will need to consult with @banesullivan to get an idea of what's available.

**Comment by banesullivan** [comment]
How do you want to display it? View the video frames interactively on the CesiumJS map? Have the video frames move in realtime?

**Comment by AlmightyYakob** [comment]
> How do you want to display it? View the video frames interactively on the CesiumJS map? Have the video frames move in realtime?

We're not exactly sure, but I think we'd be shooting for the latter. I'm also not really sure on the difference between the two approaches you mentioned.

**Comment by banesullivan** [comment]
We will be limited by: https://github.com/CesiumGS/cesium/issues/4164

see also https://cesium.com/blog/2018/06/26/implementing-materials-on-ground-primitives/

**Comment by banesullivan** [comment]
We could very easily display the total ground path of the frames in the Cesium viewer then show the movie in a `video` element on the page
